Repository service-mesh-patterns/service-mesh-patterns, pull requests merged in 2022-07, with the labels that each got.

#34 Add missing fields in istio spire design
  samples/IstioSPIRE.yaml
Labels: pattern/security

#32 Adding sample pattern files for linkerd and osm testing
  samples/bookstore.yaml
  samples/emojivoto.yaml
Labels: component/applications

#39 Create site_update.md
  .github/ISSUE_TEMPLATE/site_update.md
Labels: kind/chore
